### PR TITLE
Beta2 rollout

### PR DESCRIPTION
**Pull request by beijbom**
This is the base-branch for the new back-end rollout:

- [x] Spacer integration. Issue #264 
- [x] Switch to running jobs through AWS Batch [@beijbom ]
- [x] Add tables to track all backend jobs. Cut reliance of SQS to track completed jobs. [@beijbom]
- [x] Unskip currente backend tests. [@StephenChan ]
- [x] More vision backend tests. [@StephenChan ]
- [x] Support for different extractors. Issue #235  [@StephenChan ]

BONUS (can be pushed to later)
- [ ] More vision backend tests & SWE [@beijbom ]
- [ ] Purge python 2.7 compatibility code. Issue #364 [@StephenChan ]
- [ ] Make reg-tests robust for all settings. Add comparison for classifier performance. [@beijbom]

### CODE REVIEW

**Comment by beijbom** [comment]
@StephenChan : I merged the first PR. Do you want to take a stab next? You can address any combination of your 3 items in the PR description. Doesn't seem the order matter that much.

**Comment by StephenChan** [comment]
> Do you want to take a stab next and address any combination of your 3 items in the PR description. Doesn't seem like the order matter that much. Once done I'll take one more pass on the `vision_backend` app.

Sure. I can do 1) more vision backend tests and 3) support for different extractors. The second item, 'Purge python 2.7 compatibility code', doesn't necessarily have to happen before the rollout. Though I'll make sure to use Py3-only code for this branch.

**Comment by beijbom** [comment]
Great. Let’s test explicitly for duplicate row/col values. I didn’t handle
that explicitly, so I’m curious if it works out anyways.

**Comment by StephenChan** [comment]
> Great. Let’s test explicitly for duplicate row/col values. I didn’t handle that explicitly, so I’m curious if it works out anyways.

Agreed, there should be tests for that.

Also, a follow-up on the string-attribute related migrations from PR #324:

> Just in case, I'll set up a Python 3 environment on our staging server and see if that encounters any issues with the new migrations.

I set up Python 3 on the staging server. The migration unit test fails, just like on Travis. However, the migration itself seems okay. I ran the images 0024 migration, and started the staging server. Didn't see any issues with existing metadata. Rolled it back to 0023, still no issues seen. So it's likely the unit test's issue.

**Review by StephenChan — APPROVED** [review]
This looks finally ready to go, as far as I can tell.

@beijbom Any other loose ends you can think of, besides the announcement blog post?

**Comment by beijbom** [comment]
Very nice! Nope; this should be good to go!

**Comment by kriegman** [comment]
Yeah.

I'll have the Blog post for the feature extractor/classifier fully drafted
tonight.

But that's not really an announcement of the full release.

**Pull request merged**
