### PR TITLE
API: basics, token authentication, basic rate limiting, and start on deploy

### PR DESCRIPTION
**Pull request by StephenChan**
For #189, and a start on #231. If you're wondering why I worked on both at once: I needed an endpoint to test the base API functionality, and I figured it might as well be the deploy endpoint.

Update notes:

- The package `djangorestframework` was added (for various API conveniences).

- The package `six` was updated (for the collections_abc import).

- A new migration was added to the new app `api_core` (the new models represent asynchronous jobs whose statuses can be API-queried).

- Unit tests are now PostgreSQL-only (cannot run using SQLite) for the time being. I used JSONField in the new models, and that field is only supported in PostgreSQL with our current setup. When we are on Python 3, there should be a couple of solutions available to get JSONField working in SQLite. (I will make a separate issue with the details on this.)

Summary of changes:

- Implements a REST API with two types of authentication, 'session' and 'token'.

  - In session authentication, you simply log into the website as normal using a browser, then navigate to an API URL.

  - In token authentication, you make a POST request to the `token_auth` view with your username and password, and you get a token in the response. You then include this token in an `HTTP_AUTHORIZATION` header for any subsequent requests. This is better suited towards external applications such as command line, because this way they don't have to deal with cookies or CSRF protocol.

  - For simplicity, no OAuth2 for now, as discussed in [this comment](https://github.com/beijbom/coralnet/issues/189#issuecomment-562326884). Essentially, OAuth2 is tokens + third-party app authorization.
  
- Creates an ApiJob model to store job status and results, and an ApiJobUnit model to store status/results of a job's individual tasks (e.g. extract features for image 1, classify image 2, etc.). Jobs and job units are cleaned up (via `clean_up_old_api_jobs`) 1 month after the job has finished.

  - An alternative design would be to have only one model, ApiJob (without ApiJobUnit), and have all of an ApiJob's async tasks update fields on the ApiJob. However, this would have required a lot more care to prevent race conditions.

- Creates deploy, deploy_statuses, and deploy_results API endpoints according to our API spec draft. (I've made a few minor changes/suggestions to the spec, by the way.)
  
  - Implements permissions as follows: you need to be able to view a classifier's source to deploy that classifier, and you need to be the user who requested a deploy to view its status/results. Also, you need to be authenticated (via token or session) to use any of the deploy endpoints.
  
- Implements basic rate limiting: a 'burst' rate of 50 requests per minute, and a 'sustained' rate of 500 requests per hour. We can tweak the numbers later, of course.

Parts of deploy (#231) that aren't done yet:

- Actually downloading images from the URLs provided in the deploy request.

  - As an aside: Depending on what our users want exactly from a deploy function, we might consider making another version of deploy which takes CoralNet image IDs instead of URLs.

- Integrating with the `vision_backend` app to call spacer (or call a mock backend).

  - Relatedly, a note about the separate `vision_backend_api` app I created: In the future, if we commit more to an API-driven project design, we may want to make `vision_backend` hold the models, utils, and API views, while a new app called `vision_backend_web` holds the HTML-served views. This way the models don't have to migrate their app name. However, we're just getting started with the API now, so this separate VB-api app seems more appropriate for the time being.

### CODE REVIEW

**Comment by StephenChan** [comment]
I screwed up the `clean_up_old_api_jobs` task's logic. Need to fix that real quick.

**Comment by StephenChan** [comment]
Should be fixed.

**Comment by beijbom** [comment]
@StephenChan : I'll try to figure it out, but can you add a "how to use" somewhere? Either in this PR description, a `README.md` in the app, or add a script in the `scripts` folder?

**Comment by beijbom** [comment]
Figured out the first part:
`curl -d "username=[username]&password=[password]" http://127.0.0.1:8000/api/token-auth/`
I should be able to figure out the rest from here.

**Comment by StephenChan** [comment]
@beijbom  Think I still need your review on this before it can be merged.

**Comment by beijbom** [comment]
@StephenChan : done, you can go ahead and merge. nice work.

**Pull request merged**
