### PR TITLE
Python 3 compatibility, 'safer' changes only

### PR DESCRIPTION
**Pull request by StephenChan**
Made a lot of progress this week towards #59. This PR should do the following:

- Get the server running and all tests passing in both Python 2.7 and 3.6.
- Achieve full Python 3.6 compatibility in test-covered files.
- Make only basic compatibility changes in non-test-covered files, including:
  - Most of `vision_backend/tasks.py` and `vision_backend/task_helpers.py`. I suppose these may be largely rewritten for the pyspacer rollout anyway (@beijbom: can you confirm?).
  - Most management commands, since they either use the VB tasks or are tricky to test for some other reason (e.g. they use `SITE_DIR` directly; see #307).
  - All miscellaneous scripts: `images/scripts.py`, `vision_backend/scripts.py`, and contents of the `scripts` folder at the repo root. I didn't write tests for these because I don't know which ones have been used anytime recently.

'full Python 3.6 compatibility' just means it works in Python 3.6 (and still 2.7) as far as I can tell, and the code isn't particularly ugly for Python 3.6 purposes. I could have added a few more imports like `from six.moves import range`, `from __future__ import unicode_literals`, etc. to really make sure 2.7 ran exactly the same way as 3.6, but to me it seemed unnecessary if the tests already passed on both. Just as long as we don't write new untested code from now to the pyspacer rollout, and I don't think we plan to.

'only basic compatibility changes' means not touching the Unicode strings vs. byte strings stuff, for the most part. Just things like fixing print statements, fixing some easy imports, maybe division ops if they look straightforward enough.

Highlights in the `vision_backend` code:

- I added more tests for `confmatrix.py` and `views.py`, and also manually tested `backend_overview` in Py2 and Py3.

- It seems that numpy's integer types are descendants of the standard `int` type in certain numpy builds, but not others. If they don't descend from `int`, that means numpy's integer types can't be used directly for indexing into querysets. Hence the extra `int()` casts here and there.

Third-party package notes:

- I removed the scipy and scikit-learn dependencies, since they weren't being used as far as I could tell. Removing the deps from coralnet means that our virtualenv can simply match the scipy/scikit-learn requirements in pyspacer.

- I haven't updated the numpy version requirement yet, but I've actually been running a later version of numpy for Py3.6 testing on my machine, because numpy 1.11.1 didn't have a Py3.6 binary for me to install. In fact, the tests pass for me on numpy 1.18.1 - same as the version in https://github.com/beijbom/pyspacer/pull/10. If I'm not mistaken, all of our numpy usages are actually test-covered now, though I still wasn't sure if bumping the version could be considered a 'safe' Py3 compat move. The aforementioned integer-type problem was kind of subtle, after all.

- All the other third-party package versions are untouched. They just seemed to work in Py3.6, eerily enough!

By my judgment at least, if this PR passes review, it should be fine to merge now. Again, still Py2.7 compatible.

If I didn't forget anything, we mainly have these 'higher-risk' Python 3 compatibility changes left:

- Full Py3 compatibility for `vision_backend` (maybe wait until tasks are reworked?)
- Full Py3 compatibility for commands/scripts (@beijbom: which ones are still being used recently? I can prioritize those.)
- Updating numpy (Edit: there's another wrinkle to this - 1.17+ is Py3 only)

I can work on these items in another branch. Then we'd have the choice of merging those changes along with the rest of the pyspacer rollout, or merging them earlier. I'm fine either way.

### CODE REVIEW

**Comment by beijbom** [comment]
@StephenChan : sorry, I must have missed this. Is this PR ready for review?

**Comment by StephenChan** [comment]
No worries. Yeah, it's ready for review.

**Comment by beijbom** [comment]
@StephenChan : I took a look at this. Looks good in general. I added `python 3.6` to Travis and all tests pass there as well as on my local dev. system.  I also bumped `tqdm` package a bit to be compatible with `pyspacer`. 

- Re. management commands: I actually use all of them still. So if you can check those, that'd be great.
- Re. the vision backend module. It is up to you. My thinking is that we will add the spacer dependency, and rework that module at the same time. Note, however, that this wont be python2 compatible, so we will have to either bump the production server to Python 3.6 first or do this on a feature branch. I suppose the same goes for the numpy update. 

- As a side-note: I tried installing `pyspacer` and importing it. It is taking a long time to import. It seems it's related to how I check connections in `config.py`. I'll take a look at that over in the spacer repo.

**Comment by beijbom** [comment]
@StephenChan : please ignore my last comment regarding spacer. It was related to my SSL certificates on python3.6 on OSX. I found a way to resolve it. https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by StephenChan** [comment]
> I added `python 3.6` to Travis and all tests pass there as well as on my local dev. system. I also bumped `tqdm` package a bit to be compatible with `pyspacer`.

Sounds good.

> * Re. management commands: I actually use all of them still. So if you can check those, that'd be great.

Okay. How about the miscellaneous scripts: `images/scripts.py`, `vision_backend/scripts.py`, and contents of the `scripts` folder at the repo root?

> * Re. the vision backend module. It is up to you. My thinking is that we will add the spacer dependency, and rework that module at the same time. Note, however, that this wont be python2 compatible, so we will have to either bump the production server to Python 3.6 first or do this on a feature branch. I suppose the same goes for the numpy update.

All right. So I guess we pick what we want to deal with:

- If we bump production to Py3.6 first, the Beta-1 `vision_backend` will need one last round of debugging for those Py3.6 compat changes, even though we plan to rework `vision_backend` very soon per issue #264.

- If we keep the rest of the Py3.6 compat changes in a feature branch, and roll that out at the same time as #264, we'll be trying Py3.6 in production for the first time while also getting it on pyspacer for the first time.

At this point I'm leaning toward the feature branch idea that you suggested. Hopefully I'm not getting complacent, but I'm feeling reasonably good about the state of the non-VB code and tests. If I can get this PR onto production now (still running Py2.7) and take care of any problems that crop up, I think the actual production switch to Py3.6 shouldn't be too bad. Compared to that, I wouldn't be particularly looking forward to debugging the Beta-1 VB, to be honest.

**Comment by beijbom** [comment]
@StephenChan : Ok. let's do the feature branch then. And to be clear: we can make it very small: basically just https://github.com/beijbom/coralnet/issues/264 and perhaps some other minor cleanups related to dropping support for 2.7. 

I'll start that once https://github.com/beijbom/coralnet/issues/302 is done. (no strict dependency; I just want to do that first).

If you fix the management commands in this PR, you can leave the rest of the misc scripts for me to clean up later.

**Comment by StephenChan** [comment]
> Ok. let's do the feature branch then. And to be clear: we can make it very small: basically just #264 and perhaps some other minor cleanups related to dropping support for 2.7.
> 
> I'll start that once #302 is done. (no strict dependency; I just want to do that first).

Okay, cool.

> If you fix the management commands in this PR, you can leave the rest of the misc scripts for me to clean up later.

For the remaining management commands, I was actually thinking of fixing them in the feature branch instead of this PR. Since most of the remaining commands use the VB tasks.

Sounds good on the misc scripts, though. (I know I wrote s3_sync, so you can leave that one for me.)

**Comment by beijbom** [comment]
> For the remaining management commands, I was actually thinking of fixing them in the feature branch instead of this PR. Since most of the remaining commands use the VB tasks.

sounds good.

**Comment by StephenChan** [comment]
Merged and now in production.

**Pull request merged**
