### PR TITLE
Annotation tool - Zoom and rotation fixes

### PR DESCRIPTION
**Pull request by StephenChan**
Zoom fix was much easier than expected. That's one part of issue #319.

But for the more serious rotation problem, I can't even replicate the browser differences anymore. So, not sure what other quick fix(es) to include in this PR yet, if any.

### CODE REVIEW

**Comment by beijbom** [comment]
Wow. That was easy indeed, although only easy if one knows where to look.

**Comment by kriegman** [comment]
Nice.

**Comment by StephenChan** [comment]
Added the fix for the recent browser-independent orientation problem: edit the annotation tool's in-memory image to remove its EXIF orientation before display. I tried some odd JPEG metadata cases and they worked fine. If there's an unexpected problem with this code, a Javascript alert should pop up letting the user know that something is wrong.

The plugin I chose, piexifjs, doesn't currently recognize EXIF data in PNG files, and so I wasn't able to edit the image EXIF for the PNG case. But none of the browsers today seem to recognize EXIF orientation in PNG anyway (indeed, EXIF was only added to the PNG spec in 2017). So this will do for the time being, but it's worth noting that PNG EXIF will probably have to be supported later.

Next steps for me here:

- Confirm whether the Chromium-specific orientation problem is fixed or not.
- Update the annotation tool Help dialog's browser-compatibility info.
- Update the production server sometime tomorrow evening.

**Comment by StephenChan** [comment]
> - Confirm whether the Chromium-specific orientation problem is fixed or not.

This is indeed fixed in 4636c2d. It was the same problem that popped up in Chrome in April 2020. I just lost track of the timeline and thought this problem happened earlier than that, for some reason. I've done some testing with older browser versions to clear up the timeline of events, which I'll re-summarize in further issue comments later.

> - Update the annotation tool Help dialog's browser-compatibility info.

Just added a commit for this.

@beijbom Let me know if you get a chance to look over the new commits today, but if not, I'll still update production this evening.

**Comment by beijbom** [comment]
@StephenChan : new changes look good. Nice work on this one!

**Comment by StephenChan** [comment]
Thanks. Server updated; will also work on a potential blog post.

**Pull request merged**
